/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Merge reachability-metadata.json (generated by GraalVM native-image agent)
 * into the corresponding native-image config files.
 *
 * <p>This is a zero-dependency standalone tool — compile once with
 * {@code javac}, then run anywhere a JDK is available.
 *
 * <p>Usage:
 * <pre>
 *     java script/native/MergeNativeImageConfig.java --target-dir PATH [--source PATH]
 * </pre>
 */
@SuppressWarnings({"unchecked", "rawtypes"})
public class MergeNativeImageConfig {

    // =========================================================================
    // Configuration
    // =========================================================================

    /**
     * Describes how a top-level source key maps to a target config file.
     *
     * @param filename target filename (e.g. "reflect-config.json")
     * @param srcKey   identifier field in source entries (e.g. "type")
     * @param tgtKey   identifier field in target entries (e.g. "name")
     * @param format   "list" for JSON-array targets, "includes" for
     *                 {@code {"resources":{"includes":[...]}}} targets
     */
    record MergeTarget(String filename, String srcKey, String tgtKey, String format) {}

    static final Map<String, MergeTarget> KEY_TO_FILE = Map.of(
            "reflection",
            new MergeTarget("reflect-config.json", "type", "name", "list"),
            "resources",
            new MergeTarget("resource-config.json", "glob", "pattern", "includes"));

    /**
     * Default source file, relative to the current working directory.
     */
    static final Path DEFAULT_SOURCE = Path.of("target", "native-image-config", "reachability-metadata.json");

    // =========================================================================
    // JSON Parser  (instance methods — kept unchanged from original)
    // =========================================================================

    private String json;
    private int index;

    /**
     * Parse a JSON file and return the result as a {@code Map<String, Object>}.
     */
    public static Map<String, Object> parseFile(Path filePath) throws IOException {
        String content = Files.readString(filePath);
        return new MergeNativeImageConfig().parseObject(content);
    }

    /**
     * Parse a JSON file that may be an array or any other JSON value.
     */
    public static Object parseAny(Path filePath) throws IOException {
        String content = Files.readString(filePath);
        return new MergeNativeImageConfig().parseAny(content);
    }

    private Map<String, Object> parseObject(String json) {
        this.json = json.trim();
        this.index = 0;
        Object result = parseValue();
        if (result instanceof Map) {
            return (Map<String, Object>) result;
        }
        throw new IllegalStateException("Root must be a JSON object");
    }

    private Object parseAny(String json) {
        this.json = json.trim();
        this.index = 0;
        return parseValue();
    }

    // ---------- parser core ----------

    private Object parseValue() {
        skipWhitespace();
        if (index >= json.length()) throw new RuntimeException("Unexpected end");
        char c = json.charAt(index);
        return switch (c) {
            case '{' -> parseObject();
            case '[' -> parseArray();
            case '"' -> parseString();
            case 't', 'f', 'n' -> parseLiteral();
            default -> {
                if (c == '-' || Character.isDigit(c)) {
                    yield parseNumber();
                }
                throw new RuntimeException("Unexpected character: " + c);
            }
        };
    }

    private Map<String, Object> parseObject() {
        Map<String, Object> map = new LinkedHashMap<>();
        index++; // skip '{'
        skipWhitespace();
        if (json.charAt(index) == '}') {
            index++;
            return map;
        }
        while (true) {
            skipWhitespace();
            if (json.charAt(index) != '"') {
                throw new RuntimeException("Expected string key");
            }
            String key = parseString();
            skipWhitespace();
            if (json.charAt(index) != ':') {
                throw new RuntimeException("Expected ':'");
            }
            index++; // skip ':'
            Object value = parseValue();
            map.put(key, value);
            skipWhitespace();
            char next = json.charAt(index);
            if (next == '}') {
                index++;
                break;
            } else if (next == ',') {
                index++;
                // continue
            } else {
                throw new RuntimeException("Expected ',' or '}'");
            }
        }
        return map;
    }

    private List<Object> parseArray() {
        List<Object> list = new ArrayList<>();
        index++; // skip '['
        skipWhitespace();
        if (json.charAt(index) == ']') {
            index++;
            return list;
        }
        while (true) {
            list.add(parseValue());
            skipWhitespace();
            char next = json.charAt(index);
            if (next == ']') {
                index++;
                break;
            } else if (next == ',') {
                index++;
            } else {
                throw new RuntimeException("Expected ',' or ']'");
            }
        }
        return list;
    }

    private String parseString() {
        index++; // skip opening quote
        StringBuilder sb = new StringBuilder();
        while (index < json.length()) {
            char c = json.charAt(index);
            if (c == '"') {
                index++; // skip closing quote
                return sb.toString();
            }
            if (c == '\\') {
                // escape handling (simplified, supports common escapes)
                index++;
                char esc = json.charAt(index);
                switch (esc) {
                    case '"':
                        sb.append('"');
                        break;
                    case '\\':
                        sb.append('\\');
                        break;
                    case '/':
                        sb.append('/');
                        break;
                    case 'b':
                        sb.append('\b');
                        break;
                    case 'f':
                        sb.append('\f');
                        break;
                    case 'n':
                        sb.append('\n');
                        break;
                    case 'r':
                        sb.append('\r');
                        break;
                    case 't':
                        sb.append('\t');
                        break;
                    case 'u': // simple skip unicode (not handled)
                        sb.append('?');
                        index += 4;
                        break;
                    default:
                        sb.append(esc);
                }
                index++;
            } else {
                sb.append(c);
                index++;
            }
        }
        throw new RuntimeException("Unterminated string");
    }

    private Number parseNumber() {
        int start = index;
        // allow sign, digits, decimal point, scientific notation (basic but usable)
        while (index < json.length()) {
            char c = json.charAt(index);
            if (c == '-' || c == '+' || c == '.' || c == 'e' || c == 'E' || Character.isDigit(c)) {
                index++;
            } else {
                break;
            }
        }
        String numStr = json.substring(start, index);
        try {
            if (numStr.contains(".") || numStr.contains("e") || numStr.contains("E")) {
                return Double.parseDouble(numStr);
            } else {
                long val = Long.parseLong(numStr);
                if (val <= Integer.MAX_VALUE && val >= Integer.MIN_VALUE) {
                    return (int) val;
                }
                return val;
            }
        } catch (NumberFormatException e) {
            throw new RuntimeException("Invalid number: " + numStr);
        }
    }

    private Object parseLiteral() {
        if (json.startsWith("true", index)) {
            index += 4;
            return true;
        }
        if (json.startsWith("false", index)) {
            index += 5;
            return false;
        }
        if (json.startsWith("null", index)) {
            index += 4;
            return null;
        }
        throw new RuntimeException("Unexpected literal");
    }

    private void skipWhitespace() {
        while (index < json.length() && Character.isWhitespace(json.charAt(index))) {
            index++;
        }
    }

    // =========================================================================
    // JSON Serializer
    // =========================================================================

    /**
     * Serialize a parsed JSON structure to a formatted JSON string,
     * including a trailing newline.
     */
    public static String toJson(Object value, int indent) {
        StringBuilder sb = new StringBuilder();
        writeValue(sb, value, indent, 0);
        sb.append('\n');
        return sb.toString();
    }

    private static void writeValue(StringBuilder sb, Object value, int indent, int level) {
        switch (value) {
            case null -> sb.append("null");
            case Boolean b -> sb.append(value);
            case Number number -> sb.append(numberToString(number));
            case String s -> writeString(sb, s);
            case Map map -> writeObject(sb, (Map<String, Object>) value, indent, level);
            case List list -> writeArray(sb, (List<Object>) value, indent, level);
            default ->
                // Fallback: treat as string
                writeString(sb, value.toString());
        }
    }

    private static void writeObject(StringBuilder sb, Map<String, Object> map, int indent, int level) {
        if (map.isEmpty()) {
            sb.append("{}");
            return;
        }
        sb.append('{');
        int childLevel = level + 1;
        boolean first = true;
        for (Map.Entry<String, Object> entry : map.entrySet()) {
            if (!first) {
                sb.append(',');
            }
            first = false;
            sb.append('\n');
            indentSpaces(sb, childLevel * indent);
            writeString(sb, entry.getKey());
            sb.append(": ");
            writeValue(sb, entry.getValue(), indent, childLevel);
        }
        sb.append('\n');
        indentSpaces(sb, level * indent);
        sb.append('}');
    }

    private static void writeArray(StringBuilder sb, List<Object> list, int indent, int level) {
        if (list.isEmpty()) {
            sb.append("[]");
            return;
        }
        sb.append('[');
        int childLevel = level + 1;
        boolean first = true;
        for (Object item : list) {
            if (!first) {
                sb.append(',');
            }
            first = false;
            sb.append('\n');
            indentSpaces(sb, childLevel * indent);
            writeValue(sb, item, indent, childLevel);
        }
        sb.append('\n');
        indentSpaces(sb, level * indent);
        sb.append(']');
    }

    /**
     * Write a JSON-escaped string (with surrounding quotes).
     */
    private static void writeString(StringBuilder sb, String str) {
        sb.append('"');
        for (int i = 0; i < str.length(); i++) {
            char c = str.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\b':
                    sb.append("\\b");
                    break;
                case '\f':
                    sb.append("\\f");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < 0x20) {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append('"');
    }

    /**
     * Convert a Number to its JSON representation.
     */
    private static String numberToString(Number n) {
        if (n instanceof Double) {
            double d = n.doubleValue();
            if (Double.isNaN(d) || Double.isInfinite(d)) {
                return "null"; // JSON does not support NaN/Infinity
            }
        }
        return n.toString();
    }

    /**
     * Append {@code count} space characters.
     */
    private static void indentSpaces(StringBuilder sb, int count) {
        sb.repeat(" ", Math.max(0, count));
    }

    // =========================================================================
    // Merge Logic
    // =========================================================================

    /**
     * Merge list-typed fields ({@code methods}, {@code fields}) from a source
     * entry into a target entry.  Nothing is ever removed.
     *
     * @return the number of new items added
     */
    private static int mergeListIntoEntry(Map<String, Object> targetEntry, Map<String, Object> srcEntry) {
        int added = 0;
        for (String listKey : List.of("methods", "fields")) {
            Object srcItemsObj = srcEntry.get(listKey);
            if (!(srcItemsObj instanceof List)) {
                continue;
            }
            List<Object> srcItems = (List<Object>) srcItemsObj;

            Object tgtItemsObj = targetEntry.get(listKey);
            List<Object> targetItems;
            if (tgtItemsObj instanceof List) {
                targetItems = (List<Object>) tgtItemsObj;
            } else {
                targetItems = new ArrayList<>();
                targetEntry.put(listKey, targetItems);
            }

            if ("methods".equals(listKey)) {
                // dedup by (name, parameterTypes)
                Set<String> existing = new HashSet<>();
                for (Object item : targetItems) {
                    if (item instanceof Map) {
                        Map<String, Object> m = (Map<String, Object>) item;
                        existing.add(methodKey(m));
                    }
                }
                for (Object item : srcItems) {
                    if (!(item instanceof Map)) {
                        continue;
                    }
                    Map<String, Object> m = (Map<String, Object>) item;
                    String key = methodKey(m);
                    if (!existing.contains(key)) {
                        targetItems.add(m);
                        existing.add(key);
                        added++;
                    }
                }
            } else { // fields
                // dedup by name
                Set<String> existingNames = new HashSet<>();
                for (Object item : targetItems) {
                    if (item instanceof Map) {
                        Object name = ((Map<String, Object>) item).get("name");
                        if (name instanceof String) {
                            existingNames.add((String) name);
                        }
                    }
                }
                for (Object item : srcItems) {
                    if (!(item instanceof Map)) {
                        continue;
                    }
                    Map<String, Object> m = (Map<String, Object>) item;
                    Object name = m.get("name");
                    if (name instanceof String && !existingNames.contains((String) name)) {
                        targetItems.add(m);
                        existingNames.add((String) name);
                        added++;
                    }
                }
            }
        }
        return added;
    }

    /**
     * Build a stable dedup key for a method entry: {@code name(paramType1,paramType2,...)}.
     */
    private static String methodKey(Map<String, Object> method) {
        StringBuilder sb = new StringBuilder();
        sb.append(method.get("name"));
        sb.append('(');
        Object params = method.get("parameterTypes");
        if (params instanceof List) {
            boolean first = true;
            for (Object p : (List<Object>) params) {
                if (!first) sb.append(',');
                first = false;
                sb.append(p);
            }
        }
        sb.append(')');
        return sb.toString();
    }

    /**
     * Merge source entries into a list-format target (e.g. reflect-config.json).
     *
     * <p>For new entries the whole entry is added (with the identifier key renamed
     * from {@code srcKey} to {@code tgtKey}).  For entries whose primary identifier
     * already exists, only list-typed fields (methods, fields) are merged.
     *
     * @return the number of newly added entries (including intra-entry additions)
     */
    private static int mergeListFormat(
            List<Object> sourceEntries, List<Object> targetList, String srcKey, String tgtKey) {
        // Build existing-id → target-entry map
        Map<String, Map<String, Object>> existingMap = new LinkedHashMap<>();
        for (Object entry : targetList) {
            if (entry instanceof Map) {
                Map<String, Object> m = (Map<String, Object>) entry;
                Object val = m.get(tgtKey);
                if (val instanceof String) {
                    existingMap.put((String) val, m);
                }
            }
        }

        int added = 0;
        for (Object srcObj : sourceEntries) {
            if (!(srcObj instanceof Map)) {
                continue;
            }
            Map<String, Object> srcEntry = (Map<String, Object>) srcObj;
            Object idObj = srcEntry.get(srcKey);
            if (!(idObj instanceof String identifier)) {
                continue;
            }

            if (existingMap.containsKey(identifier)) {
                // Merge new methods / fields into the existing entry
                added += mergeListIntoEntry(existingMap.get(identifier), srcEntry);
            } else {
                // Build target entry: rename the key, copy everything else
                Map<String, Object> newEntry = new LinkedHashMap<>(srcEntry);
                newEntry.put(tgtKey, newEntry.remove(srcKey));
                targetList.add(newEntry);
                existingMap.put(identifier, newEntry);
                added++;
            }
        }
        return added;
    }

    /**
     * Merge source entries into an includes-format target (e.g. resource-config.json).
     *
     * @return the number of newly added entries
     */
    private static int mergeIncludesFormat(
            List<Object> sourceEntries, List<Object> targetIncludes, String srcKey, String tgtKey) {
        // Build existing-id set from target includes
        Set<String> existingIds = new LinkedHashSet<>();
        for (Object entry : targetIncludes) {
            if (entry instanceof Map) {
                Object val = ((Map<String, Object>) entry).get(tgtKey);
                if (val instanceof String) {
                    existingIds.add((String) val);
                }
            }
        }

        int added = 0;
        for (Object srcObj : sourceEntries) {
            if (!(srcObj instanceof Map)) {
                continue;
            }
            Object idObj = ((Map<String, Object>) srcObj).get(srcKey);
            if (!(idObj instanceof String identifier)) {
                continue;
            }
            if (existingIds.contains(identifier)) {
                continue;
            }

            Map<String, Object> newEntry = new LinkedHashMap<>();
            newEntry.put(tgtKey, identifier);
            targetIncludes.add(newEntry);
            existingIds.add(identifier);
            added++;
        }
        return added;
    }

    /**
     * Return a default (empty) data structure for the given format.
     */
    static Object createDefaultData(String format) {
        return switch (format) {
            case "list" -> new ArrayList<>();
            case "includes" -> {
                Map<String, Object> root = new LinkedHashMap<>();
                Map<String, Object> resources = new LinkedHashMap<>();
                resources.put("includes", new ArrayList<>());
                root.put("resources", resources);
                yield root;
            }
            default -> throw new IllegalArgumentException("Unknown format: " + format);
        };
    }

    // =========================================================================
    // Main
    // =========================================================================

    /**
     * Entry point.
     *
     * <p>Arguments:
     * <ul>
     *   <li>{@code --source PATH}  — path to reachability-metadata.json
     *       (default: {@code target/native-image-config/reachability-metadata.json})
     *   <li>{@code --target-dir PATH} — directory containing native-image config files
     *       (required)
     * </ul>
     */
    public static void main(String[] args) throws IOException {
        // --- parse CLI args ---
        String sourceFile = null;
        String targetDir = null;

        for (int i = 0; i < args.length; i++) {
            switch (args[i]) {
                case "--source":
                    if (i + 1 < args.length) {
                        sourceFile = args[++i];
                    } else {
                        System.err.println("[ERROR] --source requires a value");
                        System.exit(1);
                    }
                    break;
                case "--target-dir":
                    if (i + 1 < args.length) {
                        targetDir = args[++i];
                    } else {
                        System.err.println("[ERROR] --target-dir requires a value");
                        System.exit(1);
                    }
                    break;
                default:
                    System.err.println("[ERROR] Unknown argument: " + args[i]);
                    System.err.println("Usage: java MergeNativeImageConfig.java --target-dir PATH [--source PATH]");
                    System.exit(1);
            }
        }

        if (targetDir == null) {
            System.err.println("[ERROR] --target-dir is required");
            System.err.println("Usage: java MergeNativeImageConfig.java --target-dir PATH [--source PATH]");
            System.exit(1);
        }

        if (sourceFile == null) {
            sourceFile = DEFAULT_SOURCE.toString();
        }

        // --- check source ---
        Path sourcePath = Path.of(sourceFile);
        if (!Files.isRegularFile(sourcePath)) {
            System.err.println("[ERROR] Source file not found: " + sourcePath.toAbsolutePath());
            System.err.println("  Run the GraalVM native-image agent first to generate it.");
            System.exit(1);
        }

        System.out.println("[INFO] Source: " + sourcePath.toAbsolutePath());
        Map<String, Object> source = parseFile(sourcePath);

        Set<String> sourceKeysFound = source.keySet();
        Set<String> supportedKeys = KEY_TO_FILE.keySet();
        Set<String> unsupported = new LinkedHashSet<>(sourceKeysFound);
        unsupported.removeAll(supportedKeys);
        if (!unsupported.isEmpty()) {
            System.out.println("[WARN] Unsupported top-level keys in source (skipped): " + unsupported);
            System.out.println("       Extend KEY_TO_FILE in this class to add support.");
        }

        int totalAdded = 0;
        Path targetDirPath = Path.of(targetDir);

        for (Map.Entry<String, MergeTarget> entry : KEY_TO_FILE.entrySet()) {
            String key = entry.getKey();
            MergeTarget mt = entry.getValue();

            if (!source.containsKey(key)) {
                System.out.println("[SKIP] '" + key + "' — not found in source");
                continue;
            }

            Path targetPath = targetDirPath.resolve(mt.filename());
            Object targetData;

            if (!Files.isRegularFile(targetPath)) {
                System.out.println("[NEW]  '" + mt.filename() + "' — target file not found, creating default");
                Files.createDirectories(targetDirPath);
                targetData = createDefaultData(mt.format());
                Files.writeString(targetPath, toJson(targetData, 2));
            } else {
                targetData = parseAny(targetPath);
            }

            Object srcEntriesObj = source.get(key);
            if (!(srcEntriesObj instanceof List)) {
                System.out.println("[SKIP] '" + key + "' — expected a list in source");
                continue;
            }
            List<Object> sourceEntries = (List<Object>) srcEntriesObj;

            int added;
            switch (mt.format()) {
                case "list" -> {
                    if (!(targetData instanceof List)) {
                        System.err.println("[ERROR] '" + mt.filename() + "' expected a JSON array (list).");
                        System.exit(1);
                    }
                    List<Object> targetList = (List<Object>) targetData;
                    added = mergeListFormat(sourceEntries, targetList, mt.srcKey(), mt.tgtKey());
                }
                case "includes" -> {
                    if (!(targetData instanceof Map)) {
                        System.err.println("[ERROR] '" + mt.filename() + "' expected a JSON object.");
                        System.exit(1);
                    }
                    Map<String, Object> targetMap = (Map<String, Object>) targetData;
                    Object resourcesObj = targetMap.get("resources");
                    if (!(resourcesObj instanceof Map)) {
                        System.err.println("[ERROR] '" + mt.filename() + "' missing 'resources' object.");
                        System.exit(1);
                    }
                    Object includesObj = ((Map<String, Object>) resourcesObj).get("includes");
                    if (!(includesObj instanceof List)) {
                        System.err.println("[ERROR] '" + mt.filename() + "' missing resources.includes list.");
                        System.exit(1);
                    }
                    List<Object> includes = (List<Object>) includesObj;
                    added = mergeIncludesFormat(sourceEntries, includes, mt.srcKey(), mt.tgtKey());
                }
                default -> {
                    System.out.println("[WARN] Unknown format '" + mt.format() + "' for '" + key + "' — skipped");
                    continue;
                }
            }

            Files.writeString(targetPath, toJson(targetData, 2));

            System.out.printf("[OK]   %-30s  %4d source  →  +%d new%n", mt.filename(), sourceEntries.size(), added);
            totalAdded += added;
        }

        System.out.println();
        System.out.println("[DONE] " + totalAdded + " entries added across all files.");

        if (totalAdded > 0) {
            System.out.println("  Next: run 'mvn spotless:apply' to format the JSON.");
        }
    }
}
