/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.seata.metadata;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Execute merge native image metadata tests.
 *
 * <p>This test class performs the actual merge of native image metadata
 * (reachability metadata) at build time. It reads the generated metadata
 * from the build output directory and distributes it over the source tree:
 * entries of the server and namingserver modules are merged into their
 * canonical GraalVM native image metadata file, entries of every other
 * module are merged into the per-section metadata files of the module that
 * owns the referenced class.
 *
 * <p>Unlike {@link MergeNativeImageMetadataTests}, which verifies merge
 * logic behavior, this test physically writes the merged result to disk
 * and is only executed when the environment variable
 * {@code EXECUTE_NATIVE_METADATA_MERGE_NAMINGSERVER=true} is set.
 */
class ExecuteMergeNativeImageMetadataTests {

    /** Shared Jackson ObjectMapper for reading and writing JSON. */
    private static final ObjectMapper objectMapper = new ObjectMapper();

    /**
     * Root directory of the Seata project, resolved relative to the
     * {@code test-native-metadata-merge} module (two levels up).
     */
    private static final String PROJECT_BASE =
            Paths.get("..", "..").toAbsolutePath().normalize().toString();

    /**
     * Merges the namingserver's generated reachability metadata into its
     * canonical native image metadata file.
     *
     * <p>Source: {@code target/native-image-config/reachability-metadata.json}
     * (generated by the native image agent during build).
     *
     * <p>Targets: {@code namingserver/src/main/resources/META-INF/native-image/reachability-metadata.json}
     * (versioned alongside the source code) and the metadata files of the
     * library modules that own the remaining entries.
     *
     * <p>Only runs when the environment variable
     * {@code EXECUTE_NATIVE_METADATA_MERGE_NAMINGSERVER=true} is set.
     */
    @Test
    @EnabledIfEnvironmentVariable(named = "EXECUTE_NATIVE_METADATA_MERGE_NAMINGSERVER", matches = "true")
    void namingServer() throws IOException {

        // Generated metadata from the build output directory
        String source = PROJECT_BASE + "/target/native-image-config/reachability-metadata.json";
        // Canonical metadata file in the namingserver source tree; entries owned
        // by another module are written into the metadata files of that module.
        Path target = Paths.get(
                PROJECT_BASE,
                "namingserver/src/main/resources/META-INF/native-image/"
                        + NativeImageMetadataDistributor.UNIFIED_METADATA_FILE);

        JsonNode sourceNode = objectMapper.readTree(new File(source));

        distributor().distribute(sourceNode, target);
    }

    /**
     * Merges the server's generated reachability metadata into its
     * canonical native image metadata file.
     *
     * <p>Source: {@code target/native-image-config/reachability-metadata.json}
     * (generated by the native image agent during build).
     *
     * <p>Targets: {@code server/src/main/resources/META-INF/native-image/reachability-metadata.json}
     * (versioned alongside the source code) and the metadata files of the
     * library modules that own the remaining entries.
     *
     * <p>Only runs when the environment variable
     * {@code EXECUTE_NATIVE_METADATA_MERGE_SERVER=true} is set.
     */
    @Test
    @EnabledIfEnvironmentVariable(named = "EXECUTE_NATIVE_METADATA_MERGE_SERVER", matches = "true")
    void server() throws IOException {

        // Generated metadata from the build output directory
        String source = PROJECT_BASE + "/target/native-image-config/reachability-metadata.json";
        // Canonical metadata file in the server source tree; entries owned by
        // another module are written into the metadata files of that module.
        Path target = Paths.get(
                PROJECT_BASE,
                "server/src/main/resources/META-INF/native-image/"
                        + NativeImageMetadataDistributor.UNIFIED_METADATA_FILE);

        JsonNode sourceNode = objectMapper.readTree(new File(source));

        distributor().distribute(sourceNode, target);
    }

    /**
     * Creates the distributor that writes every entry into the metadata files
     * of the module that owns the referenced class.
     *
     * @return the distributor of this project
     * @throws IOException when the project sources cannot be indexed
     */
    private static NativeImageMetadataDistributor distributor() throws IOException {
        return new NativeImageMetadataDistributor(ProjectModuleResolver.forProject(Paths.get(PROJECT_BASE)));
    }
}
